### PR TITLE
added thumbnail and max_toot_chars attributes to instance object

### PR DESCRIPTION
**Pull request by theZacAttacks**

### CODE REVIEW

**Comment by maxine-red** [comment]
What does the "max_toot_chars" attribute do in particular?

**Comment by theZacAttacks** [comment]
glitchsoc instances expose their post character count via max_toot_chars

on vanilla mastodon instances this is nil

**Comment by maxine-red** [comment]
I'm merging it then.

Also a lot of thanks for the continuous help!

**Comment by theZacAttacks** [comment]
No problem! Thanks for merging my requests! :3

**Pull request merged**
